# Generated by Django 5.0.7 on 2024-07-29 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=200)),
                ('barcode', models.CharField(max_length=50)),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='provider.providers')),
            ],
        ),
    ]
